server {
        listen                  80;

        location / {
        root            /var/www/client;
        index           index.html;
        try_files       $uri $uri/ /index.html;
        includes        /etc/nginx/includes/proxy.conf;
        }

        location /api/ {

        proxy_pass   http://backend:9001;
        includes     /etc/nginx/includes/proxy.conf;

        }
}